### ISSUE TITLE
Getting Price data causes error: TypeError: unsupported type for timedelta seconds component: NoneType

### ISSUE THREAD

**Issue by novalx** [JECSand/yahoofinancials#14]
I have a list of about 250 stock symbols (e.g. 'AAPL', 'IBM', 'QQQ', ...) and try to fetch price data from Yahoo Finance.

    nr_periods = 333

    date_N_days_ago = (datetime.now() - timedelta(days = nr_periods)).strftime('%Y-%m-%d')
    date_today = datetime.now().strftime('%Y-%m-%d')

    yahoo_financials = YahooFinancials(symbols_list)
    hist_prices = yahoo_financials.get_historical_price_data(date_N_days_ago, date_today, 'daily')

This code causes the error message:

The problem is that this error message doesn't arise everytime I execute the code but randomly. I couldn't figure out why. Here is the full stack trace

    Traceback (most recent call last):
      File "testfile.py", line 273, in <module>
        updatePrices(logger)
      File "testfile.py", line 185, in updatePrices
        hist_prices = yahoo_financials.get_historical_price_data(date_N_days_ago, date_today, 'daily')
      File "/usr/local/lib/python3.5/dist-packages/yahoofinancials/__init__.py", line 547, in get_historical_price_data
        return self.get_stock_data('history', hist_obj=hist_obj)
      File "/usr/local/lib/python3.5/dist-packages/yahoofinancials/__init__.py", line 428, in get_stock_data
        dict_ent = self._create_dict_ent(tick, statement_type, tech_type, report_name, hist_obj)
      File "/usr/local/lib/python3.5/dist-packages/yahoofinancials/__init__.py", line 364, in _create_dict_ent
        cleaned_re_data = self._clean_historical_data(re_data)
      File "/usr/local/lib/python3.5/dist-packages/yahoofinancials/__init__.py", line 270, in _clean_historical_data
        cleaned_date = self.format_date(v)
      File "/usr/local/lib/python3.5/dist-packages/yahoofinancials/__init__.py", line 111, in format_date
        form_date = str((datetime.datetime(1970, 1, 1) + datetime.timedelta(seconds=in_date)).date())
    TypeError: unsupported type for timedelta seconds component: NoneType

I've even tried to hardcode the date but receive same error message (randomly). 
`hist_prices = yahoo_financials.get_historical_price_data('2017-11-20', '2018-10-19', 'daily')`

**Comment by JECSand** [comment]
Hi Novalx!

Thank you so much for bringing this issue to my attention. I apologize for you having to deal with it. 

Based on your issue submission (Note: I have not been able to recreate your bug yet FYI) It seems _get_api_data(api_url) starting on line 304 maybe returning a null or bad value for the datetime. Is this completely random or does it only happen to certain symbols? If completely random it maybe some sort of timeout issue or rate issue I may need to address with a recursive retry request. If only certain symbols do this, I'd need to build in an edge case handler for that.

To help me to this end, could you by chance send me the list of symbols you are trying to run? You can either post here or email it to sandersconnor1@gmail.com. Also it seems you are using python 3.5, can you also let me know which operating system you are running? I need to recreate this issue before anything else.

Thanks!

Connor
